### PR TITLE
TigerGraph implementation of LDBC ACID tests

### PR DESCRIPTION
**Pull request by yczhang1017**

### CODE REVIEW

**Review by jackwaudby — COMMENTED** [review]
This looks good to me. Running tests locally to double check.

**Comment by jackwaudby** [comment]
@yczhang1017 I'm following the instructions in the README. Any ideas why I run into this? 

```
docker exec --user tigergraph -it acid-tg bash -c "export PATH=/home/tigergraph/tigergraph/app/cmd:\$PATH; gadmin start all; gsql /tigergraph/setup.gsql"
[   Info] Starting EXE
[   Info] Starting CTRL
[   Info] Starting ZK ETCD DICT KAFKA ADMIN GSE NGINX GPE RESTPP KAFKASTRM-LL KAFKACONN TS3SERV GSQL TS3 IFM GUI
Connection refused.
```

**Comment by szarnyasg** [comment]
Your command seems to be missing the port mappings

**Comment by jackwaudby** [comment]
I'm on MacOS High Sierra (cos of weird uni restrictions). The docker container is starting fine via `run`. I'll try on my other machine, that runs Monterey.

**Comment by szarnyasg** [comment]
@yczhang1017 could you please tick "Allow edits by maintainers"?
image

**Comment by jackwaudby** [comment]
@yczhang1017 I have a problem with the `io.github.karol_brejna_i.tigergraph:restpp-client:1.0.0` dependency, gradle can't seem to find it on jcenter. I fixed it by installing locally but now it causes CI to fail in my PR #10

**Comment by jackwaudby** [comment]
No I didn't, however that wouldn't explain why the CI is failing: https://app.circleci.com/pipelines/github/ldbc/ldbc_acid/97/workflows/ad6e985b-5286-4857-8d1b-f4458cfa88ba/jobs/98?invite=true#step-106-80

```
> Could not find io.github.karol_brejna_i.tigergraph:restpp-client:1.0.0.
     Searched in the following locations:
- https://repo.maven.apache.org/maven2/io/github/karol_brejna_i/tigergraph/restpp-client/1.0.0/restpp-client-1.0.0.pom
       - https://repo.maven.apache.org/maven2/io/github/karol_brejna_i/tigergraph/restpp-client/1.0.0/restpp-client-1.0.0.jar
       - file:/home/circleci/.m2/repository/io/github/karol_brejna_i/tigergraph/restpp-client/1.0.0/restpp-client-1.0.0.pom
       - https://jcenter.bintray.com/io/github/karol_brejna_i/tigergraph/restpp-client/1.0.0/restpp-client-1.0.0.pom
       - file:/home/circleci/project/lib/restpp-client-1.0.0.jar
       - file:/home/circleci/project/lib/restpp-client.jar
```

**Comment by szarnyasg** [comment]
Fixed the dependency issue by adding this repository to the Gradle config: https://github.com/ldbc/ldbc_snb_interactive_impls/blob/63627976e45fb549c66a95ee66fb40f2891ac9a7/tigergraph/pom.xml#L47-L58

The  build is still failing, looking into it ...

**Comment by szarnyasg** [comment]
@yczhang1017 @karol-brejna-i the build is failing as it's unable to resolve this dependency:

```bash
    compile "io.github.karol_brejna_i.tigergraph:restpp-client:1.0.0"
```

This seems a stable version while the Sonatype repository only has SNAPSHOT versions:
https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/karol-brejna-i/tigergraph/restpp-client/

Could you please clarify which version to use and where to obtain it from? Thanks!

**Comment by karol-brejna-i** [comment]
For now, there is no release version of the dependency.
Only SNAPSHOT is available.

@yczhang1017 Let's discuss if new/stable version should be published.

**Comment by szarnyasg** [comment]
Thanks! I added this to the Gradle config and now the build is green. Will merge this as part of #10

**Pull request merged**
